services:
  - type: web
    name: knowBuy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false 
    plan: free
    disk:
      name: knowbuy-disk
      mountPath: /data
      sizeGB: 2
    build:
      pythonVersion: 3.10
