services:
  - type: web
    name: knowBuy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  
    plan: free
    build:
      pythonVersion: 3.10
